import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";

/**
 * The published package is the REPO ROOT, so `files` is the only thing standing between npm and the
 * whole checkout — `plans/`, `attachments/`, `scratch/`, `.fray/`, agent scratchpads, every worktree
 * under `.claude/`. When the package lived in `packages/cli` a mistake here shipped a few stray files;
 * now it can ship the repository. npm excludes `.git` and `node_modules` on its own and nothing else.
 *
 * These assertions are deliberately about the MANIFEST rather than a real `npm pack`: packing runs the
 * full prepack build (web bundle included), which is far too slow for the unit suite. What they catch
 * is the realistic regression — someone widening `files` — not a packing engine bug.
 */
const manifest = JSON.parse(
  readFileSync(join(import.meta.dirname, "..", "package.json"), "utf8")
) as { files?: string[]; bin?: Record<string, string>; name?: string };

/** Build outputs only. Every entry is regenerated by prepack and none is checked in. */
const PUBLISHED_PATHS = ["dist", "web-dist", "runtime"];

test("the published package ships only build output, never repository content", () => {
  assert.deepEqual(manifest.files, PUBLISHED_PATHS);
});

test("no files entry can escape the package root or widen to the whole checkout", () => {
  for (const entry of manifest.files ?? []) {
    assert.ok(!entry.startsWith("/"), `absolute files entry: ${entry}`);
    assert.ok(!entry.includes(".."), `files entry escapes the package root: ${entry}`);
    assert.ok(
      !["*", ".", "./", "**", "**/*"].includes(entry),
      `files entry publishes the entire checkout: ${entry}`
    );
  }
});

test("every bin target resolves inside a published directory", () => {
  const bins = Object.values(manifest.bin ?? {});
  assert.ok(bins.length > 0, "the package must expose a bin");
  for (const target of bins) {
    const normalized = target.replace(/^\.\//, "");
    assert.ok(
      PUBLISHED_PATHS.some((dir) => normalized.startsWith(`${dir}/`)),
      `bin ${target} is not inside a published directory, so the installed CLI would be missing`
    );
  }
});
